# -*- coding: utf-8 -*-
"""Job_pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qS1zGgXXeweltU_QCgv-EO4HO_oa5R5F
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import matplotlib.pyplot as plt

data=pd.read_csv('student_data.csv')

data

data.info()

data.isnull().sum()

data.describe()

cat_col=data.select_dtypes(include=["object"]).columns
num_col=data.select_dtypes(include=["number"]).columns

from sklearn.impute import SimpleImputer
imp_cat = SimpleImputer(strategy='most_frequent')
data[['company_type', 'job_role']] = imp_cat.fit_transform(data[['company_type', 'job_role']])

"""EDA

"""



import seaborn as sns

correlation_data = data.drop(columns=['student_id'])
numerical_cols = correlation_data.select_dtypes(include=np.number).columns
corr_matrix = correlation_data[numerical_cols].corr()
plt.figure(figsize=(18, 15))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Heatmap of Numerical Features', fontsize=16)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

lable_col=['branch','company_type','job_role']
le=LabelEncoder()
for col in lable_col:
    data[col]=le.fit_transform(data[col])

filter_data=data.drop('student_id',axis=1)

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(6, 4))
sns.countplot(data=filter_data, x='placed')
plt.title('Distribution of Placed Students')
plt.xlabel('Placed (0 = No, 1 = Yes)')
plt.ylabel('Number of Students')
plt.show()

# 2. Distribution of 'salary_lpa'
plt.figure(figsize=(8, 5))
sns.histplot(data=filter_data, x='salary_lpa', kde=True, bins=30)
plt.title('Distribution of Salary (LPA)')
plt.xlabel('Salary (LPA)')
plt.ylabel('Frequency')
plt.show()

# 3. Distribution of students by 'branch'
plt.figure(figsize=(10, 6))
sns.countplot(data=data, y='branch', order=data['branch'].value_counts().index)
plt.title('Distribution of Students by Branch')
plt.xlabel('Number of Students')
plt.ylabel('Branch (Encoded)')
plt.show()

filter_data.head()

"""Here 2 model is need to build for this purpose bcz it produce output for 1.Regression and Classification ,i have to use Ensemble leraning model Stacking and Random Forest

"""

from xgboost import XGBClassifier

from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier, XGBRegressor
from sklearn.metrics import accuracy_score, mean_squared_error

# --- Classification Model (Predicting 'placed') ---
print('Building Classification Model (Predicting if placed)...')

X_cls = filter_data.drop(columns=['placed', 'salary_lpa'])
y_cls = filter_data['placed']

X_train_cls, X_test_cls, y_train_cls, y_test_cls = train_test_split(X_cls, y_cls, test_size=0.2, random_state=42)

# Initialize and train XGBClassifier
xgb_classifier = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss')
xgb_classifier.fit(X_train_cls, y_train_cls)

# Make predictions and evaluate classifier
y_pred_cls = xgb_classifier.predict(X_test_cls)
accuracy = accuracy_score(y_test_cls, y_pred_cls)
print(f'XGBoost Classifier Accuracy: {accuracy:.4f}')

print('\nBuilding Regression Model (Predicting salary_lpa)...')

X_reg = filter_data.drop(columns=['salary_lpa', 'placed'])
y_reg = filter_data['salary_lpa']

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)

xgb_regressor = XGBRegressor(random_state=42)
xgb_regressor.fit(X_train_reg, y_train_reg)
y_pred_reg = xgb_regressor.predict(X_test_reg)
mse = mean_squared_error(y_test_reg, y_pred_reg)
rmse = np.sqrt(mse)
print(f'XGBoost Regressor RMSE: {rmse:.4f}')



# Create dummy data for prediction
dummy_data_columns = X_cls.columns # Use columns from the training data
dummy_input = pd.DataFrame({
    'cgpa': [8.5],
    'branch': [0],
    'college_tier': [2],
    'python_skill': [1],
    'dsa_skill': [1],
    'ml_skill': [1],
    'web_dev_skill': [0],
    'coding_score': [60.0],
    'communication_score': [8.0],
    'aptitude_score': [85.0],
    'internships': [1],
    'projects': [4],
    'backlogs': [0],
    'resume_score': [70.0],
    'skill_score': [1],
    'company_type': [0],
    'job_role': [1]
}, columns=dummy_data_columns)

predicted_placed = xgb_classifier.predict(dummy_input)
print(f"Predicted 'placed' status for dummy data: {predicted_placed[0]} (0=Not Placed, 1=Placed)")

predicted_salary = xgb_regressor.predict(dummy_input)
print(f"Predicted 'salary_lpa' for dummy data: {predicted_salary[0]:.2f} LPA")

import joblib

joblib.dump(xgb_classifier, 'classifier.pkl')
joblib.dump(xgb_regressor, 'regressor.pkl')